# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :ci_build do
    setup_ci(provider: "travis")

    username = ENV['USERNAME']
    personal_github_access_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]
    authorization_token_str = "#{username}:#{personal_github_access_token}"
    basic_authorization_token = Base64.strict_encode64(authorization_token_str)

    match(
      git_basic_authorization:basic_authorization_token,
      app_identifier: ['jp.trap.ex.traQ', 'jp.trap.ex.traQ.traQShareExtension'],
      type: "appstore",
      readonly: true
    )

    build_app(
      scheme: "traQ-R second",
      export_method: "app-store"
    )
  end
end
