name: Build traQ

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Bundle Install
      run: bundle update --bundler
    - name: Fastlane Install
      run: bundle install
    - name: Build App
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        PERSONAL_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
      run: bundle exec fastlane ci_build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ipa-file
        path: ex-traQ.ipa
        retention-days: 5
